### ISSUE TITLE
General Python tidy

### ISSUE THREAD

**Issue by dave-donaghy** [ICLRandD/Blackstone#1]
My point of view is that I have some Python experience, but very little domain experience.

Depending on who the contributors are, it might help things if we have a more robust Python environment:

- virtual environment
- runnable code
- tests

If the imminent contributors aren't going to be Python-focussed, then that might not help, but if it does, then the benefit could be that everyone gets a common environment in which to play with this stuff early on.

**Comment by ICLRandD** [comment]
Hi Dave, many thanks for this. I'm in the process of straightening the repo out, take a look when you get a chance. 

Best,

D

**Comment by dave-donaghy** [comment]
Will do thanks!!

-------- Original Message --------
