### ISSUE TITLE
ValueError - Unknown morphological feature: 'Person' 

### ISSUE THREAD

**Issue by nicolasesprit** [ICLRandD/Blackstone#10]
Hi.
After fresh installation I wanted to test sentence segmenter example  but I get this error : 

> ValueError: [E167] Unknown morphological feature: 'Person' (2313063860588076218). This can happen if the tagger was trained with a different set of morphological features. If you're using a pretrained model, make sure that your models are up to date:
> python -m spacy validate

python -m spacy validate show me: 
TYPE      NAME             MODEL            VERSION
package   en-core-web-sm   en_core_web_sm   2.2.0     ✔

I have tested with Spacy 2.2.1 and 2.2.0 (with Python 3.6.7 / Data Science Virtual Machine form Azure with GPU)

Thank you in advance for your help

**Comment by nicolasesprit** [comment]
Duplicate of #9

**Comment by nicolasesprit** [comment]
Spacy downgraded to 2.1.8 as specified in [Issue 9](https://github.com/ICLRandD/Blackstone/issues/9)  but same issue.

C:\Users\bdl>**pip install https://blackstone-model.s3-eu-west-1.amazonaws.com/en_blackstone_proto-0.0.1.tar.gz**
Collecting https://blackstone-model.s3-eu-west-1.amazonaws.com/en_blackstone_proto-0.0.1.tar.gz
  Using cached https://blackstone-model.s3-eu-west-1.amazonaws.com/en_blackstone_proto-0.0.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): en-blackstone-proto==0.0.1 from https://blackstone-model.s3-eu-west-1.amazonaws.com/en_blackstone_proto-0.0.1.tar.gz in c:\anaconda\lib\site-packages
Requirement already satisfied: spacy>=2.1.6 in c:\users\bdl\appdata\roaming\python\python36\site-packages (from en-blackstone-proto==0.0.1) (2.1.8)
Requirement already satisfied: thinc<7.1.0,>=7.0.8 in c:\users\bdl\appdata\roaming\python\python36\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (7.0.8)
Requirement already satisfied: wasabi<1.1.0,>=0.2.0 in c:\anaconda\lib\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (0.2.2)
Requirement already satisfied: blis<0.3.0,>=0.2.2 in c:\users\bdl\appdata\roaming\python\python36\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (0.2.4)
Requirement already satisfied: preshed<2.1.0,>=2.0.1 in c:\users\bdl\appdata\roaming\python\python36\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (2.0.1)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\anaconda\lib\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (2.0.2)
Requirement already satisfied: numpy>=1.15.0 in c:\anaconda\lib\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (1.16.4)
Requirement already satisfied: srsly<1.1.0,>=0.0.6 in c:\anaconda\lib\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (0.1.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\anaconda\lib\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (2.22.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\anaconda\lib\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (1.0.2)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in c:\anaconda\lib\site-packages (from spacy>=2.1.6->en-blackstone-proto==0.0.1) (0.9.6)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in c:\anaconda\lib\site-packages (from thinc<7.1.0,>=7.0.8->spacy>=2.1.6->en-blackstone-proto==0.0.1) (4.36.1)
Requirement already satisfied: idna<2.9,>=2.5 in c:\anaconda\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.1.6->en-blackstone-proto==0.0.1) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.1.6->en-blackstone-proto==0.0.1) (2019.3.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\anaconda\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.1.6->en-blackstone-proto==0.0.1) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\anaconda\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.1.6->en-blackstone-proto==0.0.1) (3.0.4)
Building wheels for collected packages: en-blackstone-proto
  Building wheel for en-blackstone-proto (setup.py) ... done
  Created wheel for en-blackstone-proto: filename=en_blackstone_proto-0.0.1-cp36-none-any.whl size=243759407 sha256=56b2d6e198d6500707046665def5c6559efb66e54f8d63637b439db99ce8634e
  Stored in directory: C:\Users\bdl\AppData\Local\pip\Cache\wheels\a2\81\dd\09c3b4ef7899e7d9cf92ed3152d29a08b5fd80f7a8bf66df4d
Successfully built en-blackstone-proto

C:\Users\bdl>python -m spacy validate
✔ Loaded compatibility table

====================== Installed models (spaCy v2.1.8) ======================
ℹ spaCy installation:
C:\Users\bdl\AppData\Roaming\Python\Python36\site-packages\spacy

TYPE      NAME             MODEL            VERSION
package   en-core-web-sm   en_core_web_sm   2.1.0     ✔

**Comment by DeNeutoy** [comment]
This is a spacy version issue, it will be resolved in the next release with a new model.

**Comment by viva2202** [comment]
I also have the problem when using 

python -m spacy validate 

TYPE      NAME             MODEL            VERSION
package   en-core-web-sm   en_core_web_sm   2.2.0     ✔

Is there already a solution?
