### ISSUE TITLE
requirements.txt is too big

### ISSUE THREAD

**Issue by DeNeutoy** [ICLRandD/Blackstone#2]
`requirements.txt` typically only specifies the exact packages that are required to run a project, rather than an exhaustive list of your personal python environment. 

https://github.com/allenai/scispacy/blob/master/requirements.in

Also, it's typical to only pin packages to a particular version if you know there is a problem in a newer version that will break stuff. The reason for this is that it makes it easier for people to install if you don't require precise version numbers.

**Comment by ICLRandD** [comment]
Thanks, Mark. Done!
