### ISSUE TITLE
Add a `tests` directory

### ISSUE THREAD

**Issue by DeNeutoy** [ICLRandD/Blackstone#3]
I recommend using https://docs.pytest.org/en/latest/

The tests directory should look like this:

```
tests/
- __init__.py (important)
- linker_test.py
- ...
```
Then add this file to your top level directory: https://github.com/allenai/scispacy/blob/master/pytest.ini

then you should be able to run all tests just by running `pytest` in the root of the project. The directory of your tests should look like the directory of the blackstone package. Tests will only be run if the class and method names begin or end with `test`.

**Comment by ICLRandD** [comment]
Done and done!
