### ISSUE TITLE
Unknown Morphological Feature

### ISSUE THREAD

**Issue by StuartHewitson** [ICLRandD/Blackstone#9]
I am trying to get up to speed with the model but when I execute the example code given I hit the following error when nlp = spacy.load("en_blackstone_proto") is called.

[E167] Unknown morphological feature: 'ConjType' (9141427322507498425). This can happen if the tagger was trained with a different set of morphological features. If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate

**Comment by Createdd** [comment]
I have the same issue. 
Check out this issue as reference: https://github.com/huggingface/neuralcoref/issues/206
Can you update the model? It seems that it is not compatible with spacy right now. 

Executing validation shows that it is not recognized as model at all:
![image](https://user-images.githubusercontent.com/22077628/66256566-5857cf00-e78f-11e9-857e-89a735f9ee9e.png)

Also:

![image](https://user-images.githubusercontent.com/22077628/66256678-ae794200-e790-11e9-8294-e6a2a60a2f24.png)

For more infos see: https://spacy.io/usage/#upgrading

Let me know if I can help somehow.

**Comment by svlandeg** [comment]
I'm guessing that as a quick workaround, for now, you could try downgrading your spaCy version to 2.1.8 orso ?

**Comment by StuartHewitson** [comment]
Downgrading to 2.1.8 works for me.

**Comment by ICLRandD** [comment]
Apologies for the slow response to this issue @StuartHewitson and @Createdd. As @svlandeg  says (thank you, Sophie), the current work around is to downgrade your spacy. Obviously, a workaround of this sort is not ideal. 

We'll be retraining the model in November and we will not be initialising it with the `pretrain` command, which should make the model a bit more robust as new versions of spacy are released.

**Comment by mdrmuhaimin** [comment]
Are you using any language model from spacy you need to download the newer one

**Comment by connerxyz** [comment]
How exactly are you performing the downgrade?

I have run into this same issue and have yet to resolve it. `pip install spacy==2.1.8` runs into an low level error while installing build dependencies... 

```
pip install spacy==2.1.8
Looking in indexes: https://pypi.org/simple, ...
Collecting spacy==2.1.8
  Using cached https://files.pythonhosted.org/packages/58/f2/5a23bb7251988da474eec844b692760cb0a317912291afc77b516f399cff/spacy-2.1.8.tar.gz
  Installing build dependencies ... \
...
error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.7" but "10.9" during configure
```

I'm on macOS Mojave 10.14.6.

---

Edit: [this spacy issue](https://github.com/explosion/spaCy/issues/3426) got me pointed the right direction... the solution was to install with conda.

`conda install -c conda-forge spacy=2.1.8`
